### ISSUE TITLE
Filtering Pipeline

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/swan#26]
## Task
Create a workflow to screen a subset of ligands from a smiles data set using as features:
TODO:
*  [x] functional group
* [x] bulkiness
* [x] synthesizability score (SA score)

**Comment by BvB93** [comment]
[`CAT.recipes.sa_scores()`](https://cat.readthedocs.io/en/latest/12_6_recipes.html#CAT.dye.addlig.sa_scores) might be of use here in combination with https://github.com/gablg1/ORGAN/raw/master/organ/SA_score.pkl.gz.

**Comment by BvB93** [comment]
Note that the `SA_SCORE.pkl.gz` file won't be required anymore after merging https://github.com/nlesc-nano/CAT/pull/145 (planned for Monday).
