### ISSUE TITLE
Create interface to database

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/swan#35]
## Database format
besides the numerical values of the properties each table must contain the following data:
* **smile** (`string`) representing the molecule
* **Settings** (`JSON`) representing the input used to perform the calculation. It must include quantum package used(including exact version), basis set, functional, numerical tolerance, etc.
* **Optimize geometry** (`string`) XYZ format with the optimized geometry used for the calculation.
* **core** (`string`) If the molecular properties required a quantum surface to compute a property, a string in XYZ format with the molecular coordinates of the surface must be provided.
* **molecular properties** (numbers) containing the numerical values of the properties.

### Additional metadata
* **Timestamp**(when calculation was done)
* **Timestamp**(when calculation was scheduled)
* **User** who uploaded the data
* **architecture** of the machine used
* **Status** (available, unavailable, in progress, complete, failed)

## Database usage
Expected user actions:
* Get data. The user either query for some existing *molecular property* data or for some jobs that need to be computed.
* Insert data.  The user insert or update the values of a given molecular property or update the state of the computed jobs.

### Possible technologies
* Use a Non-SQL database like [Mongodb](https://www.mongodb.com/) together with [pymongo](https://pymongo.readthedocs.io/en/stable/)
* Use A SQL database like [Postgres](https://www.postgresql.org/) and the [SQLAlchemy](https://www.sqlalchemy.org/) toolkit

**Comment by JensWehner** [comment]
I am not sure how to store the results. 
We can store a json in an arbitrary format, which would make the whole thing easily extensible. 

On the other hand using like fixed fields for the individual results makes the database a lot easier.

**Comment by felipeZ** [comment]
> I am not sure how to store the results.
> We can store a json in an arbitrary format, which would make the whole thing easily extensible.
> 
> On the other hand using like fixed fields for the individual results makes the database a lot easier.

I am making an [experiment with mongodb](https://github.com/nlesc-nano/ligands_database/issues/1) to store and retrieve the data

**Comment by felipeZ** [comment]
The database is now handled by the [insilico server](https://github.com/nlesc-nano/insilico-server)
