### ISSUE TITLE
Add Support for Python 3.9

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/swan#55]
## New
* Test Python 3.9 in the CI

**Comment by BvB93** [comment]
FYI, with a bit of restructuring I managed to get it working for qmflows: https://github.com/SCM-NV/qmflows/pull/223.

**Comment by BvB93** [comment]
The key step was to create a new conda environment and then activate it in every step.

**Comment by felipeZ** [comment]
Thanks for the hint @BvB93!
