### ISSUE TITLE
Add Interface to GPytorch

### ISSUE THREAD

**Issue by felipeZ** [nlesc-nano/swan#90]
## Feature
Add interface to [GPytorch](https://gpytorch.ai/) for training Gaussian Processes on Molecules.

**Comment by NicoRenaud** [comment]
I don't think we need to link to flowmo as it is a RDKIT+scikit learn pipeline ... so pretty much what swan already does. What do you think ?

**Comment by felipeZ** [comment]
Indeed You are right. Actually, I am building an interface to [GPFlow](https://github.com/GPflow/GPflow)

**Comment by NicoRenaud** [comment]
no GpyTorch : https://gpytorch.ai/

**Comment by felipeZ** [comment]
solved by #91
